In [28]:
from backend.app.services.data_services import (
    get_available_indicators,
    get_available_strategies,
    get_strategies_metadata,
    get_available_tickers,
    _read_csv,
    fetch_data_to_df,
    get_indicators_metadata,
    _load_and_resample_data
)
from backend.app.services.cache_service import set_data, delete_data, get_key_list
from backend.app.core.Strategies import STRATEGY_REGISTRY

import asyncio
import pandas as pd
import vectorbt as vbt

In [10]:
ticker_name = 'RELIANCE INDUSTRIES LTD'
df = await _read_csv(ticker_name=ticker_name)
await set_data(df=df, ticker= ticker_name)

{'message': 'Data loaded successfully with key: data:RELIANCE INDUSTRIES LTD'}

In [22]:
# get_key_list()
# await delete_data("NIFTY 50")
# get_available_tickers()
get_available_strategies()

['EMA Crossover',
 'SMA Crossover',
 'RSI',
 'MACD',
 'Bollinger Bands',
 'VWAP',
 'ADX Trend',
 'Stochastic Oscillator',
 'CCI',
 'ROC',
 'Williams %R',
 'ATR Breakout',
 'Donchian Channel',
 'Momentum',
 'EMA + RSI',
 'Mean Reversion',
 'Price Channel',
 'RSI Divergence',
 'EMA Pullback',
 'SuperTrend']

In [31]:
resolution = "15m"
start_date = "01/12/2024 09:15:00"
end_date = "01/02/2025 09:15:00"

df = await _load_and_resample_data(ticker_name, resolution, start_date, end_date)
df.shape

d:\OneDrive - iitgn.ac.in\Desktop\HedgeOne-Quant\backend\app\services\data_services.py:54: FutureWarning:

'T' is deprecated and will be removed in a future version, please use 'min' instead.

(1101, 6)

In [63]:
strategy_fn = STRATEGY_REGISTRY["EMA Crossover"]
params = {"short_window":4, "long_window":9}

result = strategy_fn(df, **params)

portfolio = await asyncio.to_thread(
    vbt.Portfolio.from_signals,
    df["close"],
    result["entries"],
    result["exits"],
    freq=pd.Timedelta(resolution),
    init_cash=100000,
    fees=0,
    slippage=0
)

In [64]:
portfolio.stats(group_by=True)

Start                                                 0
End                                                1100
Period                                 11 days 11:15:00
Start Value                                    100000.0
End Value                                 100296.129454
Total Return [%]                               0.296129
Benchmark Return [%]                          -0.891461
Max Gross Exposure [%]                            100.0
Total Fees Paid                                     0.0
Max Drawdown [%]                               4.095371
Max Drawdown Duration                   4 days 04:30:00
Total Trades                                         50
Total Closed Trades                                  49
Total Open Trades                                     1
Open Trade PnL                               134.530077
Win Rate [%]                                  28.571429
Best Trade [%]                                 3.987521
Worst Trade [%]                               -1.447773
Avg Winning Trade [%]                          0.965438
Avg Losing Trade [%]                          -0.376293
Avg Winning Trade Duration    0 days 05:39:38.571428571
Avg Losing Trade Duration     0 days 01:02:34.285714285
Profit Factor                                  1.012335
Expectancy                                     3.297946
Sharpe Ratio                                   0.459254
Calmar Ratio                                    2.40945
Omega Ratio                                    1.011514
Sortino Ratio                                  0.662106
Name: group, dtype: object

In [65]:
portfolio.trades.records

    id  col       size  entry_idx  ...    return  direction  status  parent_id
0    0    0  75.520145         48  ... -0.003889          0       1          0
1    1    0  75.856582         68  ... -0.001333          0       1          1
2    2    0  75.735304         75  ... -0.004225          0       1          2
3    3    0  75.561990         79  ... -0.000877          0       1          3
4    4    0  75.438161         85  ...  0.004078          0       1          4
5    5    0  77.277257        174  ... -0.001789          0       1          5
6    6    0  77.121051        184  ... -0.002410          0       1          6
7    7    0  78.816356        236  ...  0.012544          0       1          7
8    8    0  80.012165        300  ... -0.000200          0       1          8
9    9    0  79.910047        318  ... -0.014478          0       1          9
10  10    0  79.780900        351  ... -0.009172          0       1         10
11  11    0  79.247691        356  ... -0.005185          0       1         11
12  12    0  79.813143        376  ... -0.000984          0       1         12
13  13    0  79.604020        395  ...  0.004913          0       1         13
14  14    0  79.487441        416  ... -0.001383          0       1         14
15  15    0  79.740813        435  ... -0.002166          0       1         15
16  16    0  79.509614        437  ... -0.001838          0       1         16
17  17    0  79.529136        451  ...  0.001801          0       1         17
18  18    0  79.412358        468  ... -0.001305          0       1         18
19  19    0  79.610694        483  ... -0.001597          0       1         19
20  20    0  79.954974        506  ... -0.001647          0       1         20
21  21    0  79.757554        517  ... -0.001646          0       1         21
22  22    0  79.593512        528  ...  0.004854          0       1         22
23  23    0  79.505635        549  ...  0.024903          0       1         23
24  24    0  79.070281        600  ... -0.008412          0       1         24
25  25    0  79.972735        626  ...  0.002186          0       1         25
26  26    0  79.792282        648  ...  0.016319          0       1         26
27  27    0  79.785956        686  ... -0.001586          0       1         27
28  28    0  79.941490        699  ... -0.008195          0       1         28
29  29    0  79.529963        707  ... -0.005268          0       1         29
30  30    0  79.345343        714  ... -0.004803          0       1         30
31  31    0  79.518034        738  ... -0.001652          0       1         31
32  32    0  79.297142        747  ... -0.003543          0       1         32
33  33    0  78.617407        750  ... -0.007771          0       1         33
34  34    0  78.929672        768  ... -0.001905          0       1         34
35  35    0  78.769740        771  ...  0.009037          0       1         35
36  36    0  78.442097        788  ...  0.039875          0       1         36
37  37    0  77.950410        850  ... -0.001032          0       1         37
38  38    0  77.971292        869  ... -0.001914          0       1         38
39  39    0  78.407222        885  ... -0.011722          0       1         39
40  40    0  77.745967        891  ... -0.004372          0       1         40
41  41    0  78.508601        919  ... -0.000589          0       1         41
42  42    0  78.774574        950  ... -0.006500          0       1         42
43  43    0  80.569988        987  ... -0.004055          0       1         43
44  44    0  80.350772       1007  ...  0.003574          0       1         44
45  45    0  80.198249       1029  ... -0.002262          0       1         45
46  46    0  80.058897       1031  ...  0.000444          0       1         46
47  47    0  79.916869       1052  ...  0.005564          0       1         47
48  48    0  79.569113       1073  ...  0.005070          0       1         48
49  49    0  79.135340       1098  ...  0.001343          0       0         49

[50 rows x 14 columns]

In [66]:
portfolio.value()

0       100000.000000
1       100000.000000
2       100000.000000
3       100000.000000
4       100000.000000
            ...
1096    100161.599377
1097    100161.599377
1098    100161.599377
1099    100185.339978
1100    100296.129454
Name: close, Length: 1101, dtype: float64

In [67]:
p = portfolio

In [68]:
p.orders.records

    id  col   idx       size    price  fees  side
0    0    0    48  75.520145  1324.15   0.0     0
1    1    0    50  75.520145  1319.00   0.0     1
2    2    0    68  75.856582  1313.15   0.0     0
3    3    0    69  75.856582  1311.40   0.0     1
4    4    0    75  75.735304  1313.50   0.0     0
..  ..  ...   ...        ...      ...   ...   ...
94  94    0  1052  79.916869  1240.10   0.0     0
95  95    0  1068  79.916869  1247.00   0.0     1
96  96    0  1073  79.569113  1252.45   0.0     0
97  97    0  1094  79.569113  1258.80   0.0     1
98  98    0  1098  79.135340  1265.70   0.0     0

[99 rows x 7 columns]

In [69]:
d = pd.DataFrame(p.positions.records)
d.columns

Index(['id', 'col', 'size', 'entry_idx', 'entry_price', 'entry_fees',
       'exit_idx', 'exit_price', 'exit_fees', 'pnl', 'return', 'direction',
       'status', 'parent_id'],
      dtype='object')

In [70]:
d.head()

   id  col       size  entry_idx  ...    return  direction  status  parent_id
0   0    0  75.520145         48  ... -0.003889          0       1          0
1   1    0  75.856582         68  ... -0.001333          0       1          1
2   2    0  75.735304         75  ... -0.004225          0       1          2
3   3    0  75.561990         79  ... -0.000877          0       1          3
4   4    0  75.438161         85  ...  0.004078          0       1          4

[5 rows x 14 columns]

In [71]:
p.plot()

FigureWidget({
    'data': [{'legendgroup': '0',
              'line': {'color': '#1f77b4'},
              'name': 'Close',
              'showlegend': True,
              'type': 'scatter',
              'uid': '49f44a5b-19c5-4f22-be38-1f1f8927e250',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': ('MzMzMzP7k0BmZmZmZhSUQAAAAAAAGJ' ... 'zMzMzGk0AAAAAAAMiTQJqZmZmZzZNA'),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'customdata': {'bdata': ('AAAAAAAAAAAboD8OSuFSQAAAAAAAAA' ... 'AAAACAWEAbCZNnqchTQAAAAAAAAAAA'),
                             'dtype': 'f8',
                             'shape': '50, 3'},
              'hovertemplate': ('Order Id: %{customdata[0]}<br>' ... '<br>Fees: %{customdata[2]:.6f}'),
              'legendgroup': '1',
              'marker': {'color': '#37B13F',
                         'line': {'color': 'rgb(38,123,44)', 'width': 1},
                         'size': 8,
                         'symbol': 'triangle-up'},
              'mode': 'markers',
              'name': 'Buy',
              'type': 'scatter',
              'uid': 'f0ca5453-a513-421a-916a-3c747818c3f2',
              'x': {'bdata': ('MABEAEsATwBVAK4AuADsACwBPgFfAW' ... 'N7A5cDtgPbA+8DBQQHBBwEMQRKBA=='),
                    'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': ('mpmZmZmwlECamZmZmYSUQAAAAAAAhp' ... 'ZmYJNAzczMzMyRk0DNzMzMzMaTQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'customdata': {'bdata': ('AAAAAAAA8D8boD8OSuFSQAAAAAAAAA' ... 'AAAABAWEAk2bRYbORTQAAAAAAAAAAA'),
                             'dtype': 'f8',
                             'shape': '49, 3'},
              'hovertemplate': ('Order Id: %{customdata[0]}<br>' ... '<br>Fees: %{customdata[2]:.6f}'),
              'legendgroup': '2',
              'marker': {'color': '#EA4335',
                         'line': {'color': 'rgb(181,31,18)', 'width': 1},
                         'size': 8,
                         'symbol': 'triangle-down'},
              'mode': 'markers',
              'name': 'Sell',
              'type': 'scatter',
              'uid': '42a40fdb-d431-4017-a2bf-f969d8908e2f',
              'x': {'bdata': ('MgBFAE4AUwBkALMAuwAAATcBRQFgAW' ... 'oDdwN+A54DuAPkA/8DBgQTBCwERgQ='),
                    'dtype': 'i2'},
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAACclECamZmZmX2UQM3MzMzMb5' ... 'mZmVeTQAAAAAAAfJNAMzMzMzOrk0A='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'customdata': {'bdata': ('AAAAAAAAEEAAAAAAAAAQQADh+K2BOX' ... 'AAAEhAAEzSzDiUf0BhUjGWWMR0Pw=='),
                             'dtype': 'f8',
                             'shape': '14, 4'},
              'hovertemplate': ('Exit Trade Id: %{customdata[0]' ... 'r>Return: %{customdata[3]:.2%}'),
              'legendgroup': '3',
              'marker': {'color': '#37B13F',
                         'line': {'color': 'rgb(38,123,44)', 'width': 1},
                         'opacity': {'bdata': ('zkoJUh146D+9CoNCVH7pP63e4er4ke' ... 'KVB+g/RPPqliSm6D+gELfP15boPw=='),
                                     'dtype': 'f8'},
                         'size': {'bdata': ('XjQ2Cau8HkBS36hsIFsiQPOSJVqBUx' ... 'w9LBxAYuCvxSrJH0Cni1bm6m8fQA=='),
                                  'dtype': 'f8'},
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Closed - Profit',
              'type': 'scatter',
              'uid': '1732be67-545f-4b74-abc3-b7d2a7594c2d',
              'x': {'bdata': 'ZAAAAZwB0gEkAlMChAKiAhEDUQP/AxMELARGBA==', 'dtype': 'i2'},
              'xaxis': 'x2',
              'y': {'bdata': ('VTXHwvyzcD+vVivj07CJP54wwyBxH3' ... 'JxIT0/GlM1+VjKdj9hUjGWWMR0Pw=='),
                    'dtype': 'f8'},
              'yaxis': 'y2'},
             {'customdata': {'bdata': ('AAAAAAAAAAAAAAAAAAAAAACFiyXcTn' ... 'AAgEZAAD4XWcMRbMCkcLqeJ4divw=='),
                             'dtype': 'f8',
                             'shape': '35, 4'},
              'hovertemplate': ('Exit Trade Id: %{customdata[0]' ... 'r>Return: %{customdata[3]:.2%}'),
              'legendgroup': '4',
              'marker': {'color': '#EA4335',
                         'line': {'color': 'rgb(181,31,18)', 'width': 1},
                         'opacity': {'bdata': ('i4lQ40Vy6D9UOER0FyPoP1jrGmuufO' ... 'cgw+g/wkPPjmt36D97Hdp03T/oPw=='),
                                     'dtype': 'f8'},
                         'size': {'bdata': ('q3cArpeaHkA/8417s8wcQIAHHcZO1x' ... 'EeOSBA6rVjFp64HkD2q03Ui3QdQA=='),
                                  'dtype': 'f8'},
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Closed - Loss',
              'type': 'scatter',
              'uid': '3ff9f4ee-d58a-4692-838b-9fab2b5cf286',
              'x': {'bdata': ('MgBFAE4AUwCzALsANwFFAWABagGDAa' ... 'LxAgEDWwNqA3cDfgOeA7gD5AMGBA=='),
                    'dtype': 'i2'},
              'xaxis': 'x2',
              'y': {'bdata': ('CI9GT23cb7/DpBYbo9VVv05dNVKaTn' ... 'ekn3q/xe1/V3qccL+kcLqeJ4divw=='),
                    'dtype': 'f8'},
              'yaxis': 'y2'},
             {'customdata': {'bdata': 'AAAAAACASEAAAAAAAIBIQACU1mT20GBABY8eKX8BVj8=', 'dtype': 'f8', 'shape': '1, 4'},
              'hovertemplate': ('Exit Trade Id: %{customdata[0]' ... 'r>Return: %{customdata[3]:.2%}'),
              'legendgroup': '5',
              'marker': {'color': '#FFAA00',
                         'line': {'color': 'rgb(178,118,0)', 'width': 1},
                         'opacity': {'bdata': 'GeYCXWoj6D8=', 'dtype': 'f8'},
                         'size': {'bdata': '5uiQHpfOHEA=', 'dtype': 'f8'},
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Open',
              'type': 'scatter',
              'uid': '9a6c855c-a805-4174-b4ae-0b01d9c6842a',
              'x': {'bdata': 'TAQ=', 'dtype': 'i2'},
              'xaxis': 'x2',
              'y': {'bdata': 'BY8eKX8BVj8=', 'dtype': 'f8'},
              'yaxis': 'y2'},
             {'legendgroup': '6',
              'line': {'color': '#7f7f7f'},
              'name': 'Benchmark',
              'showlegend': True,
              'type': 'scatter',
              'uid': '8995974c-dc79-4031-bc48-8470c110bdd0',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AAAAAAAA8D8efo3NLRTwPyOQWMYPF/' ... 'PL0RSs7z+n//3MAK7vP7Q3krb4tu8/'),
                    'dtype': 'f8'},
              'yaxis': 'y3'},
             {'hoverinfo': 'skip',
              'legendgroup': '7',
              'line': {'color': 'rgba(0, 0, 0, 0)', 'width': 0},
              'opacity': 0,
              'showlegend': False,
              'type': 'scatter',
              'uid': 'ab09fc9d-aa82-4903-8d4c-aeca1e7cbe77',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAABAAAA'),
                    'dtype': 'i4'},
              'yaxis': 'y3'},
             {'connectgaps': False,
              'fill': 'tonexty',
              'fillcolor': 'rgba(0, 128, 0, 0.3)',
              'hoverinfo': 'skip',
              'legendgroup': '7',
              'line': {'color': 'rgba(0, 0, 0, 0)', 'width': 0},
              'opacity': 0,
              'showlegend': False,
              'type': 'scatter',
              'uid': '0ad3881d-3578-45ed-ba82-cf98299b3da0',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AAAAAAAA8D8AAAAAAADwPwAAAAAAAP' ... 'EGfp4G8D+HZjdulwfwP0w8cyQhDPA/'),
                    'dtype': 'f8'},
              'yaxis': 'y3'},
             {'hoverinfo': 'skip',
              'legendgroup': '7',
              'line': {'color': 'rgba(0, 0, 0, 0)', 'width': 0},
              'opacity': 0,
              'showlegend': False,
              'type': 'scatter',
              'uid': '159e6207-fa89-4d5c-91ac-08be6fd6d96f',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAABAAAA'),
                    'dtype': 'i4'},
              'yaxis': 'y3'},
             {'connectgaps': False,
              'fill': 'tonexty',
              'fillcolor': 'rgba(255, 0, 0, 0.3)',
              'hoverinfo': 'skip',
              'legendgroup': '7',
              'line': {'color': 'rgba(0, 0, 0, 0)', 'width': 0},
              'opacity': 0,
              'showlegend': False,
              'type': 'scatter',
              'uid': '3c793859-109b-40c9-af92-69ad4972fc74',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AAAAAAAA8D8AAAAAAADwPwAAAAAAAP' ... 'AAAAAA8D8AAAAAAADwPwAAAAAAAPA/'),
                    'dtype': 'f8'},
              'yaxis': 'y3'},
             {'legendgroup': '8',
              'line': {'color': '#9467bd'},
              'name': 'Value',
              'showlegend': True,
              'type': 'scatter',
              'uid': '964f86f0-466d-4f04-a938-90176fb8a94b',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AAAAAAAA8D8AAAAAAADwPwAAAAAAAP' ... 'EGfp4G8D+HZjdulwfwP0w8cyQhDPA/'),
                    'dtype': 'f8'},
              'yaxis': 'y3'},
             {'hoverinfo': 'skip',
              'legendgroup': '7',
              'line': {'color': 'rgba(0, 0, 0, 0)', 'width': 0},
              'opacity': 0.0,
              'showlegend': False,
              'type': 'scatter',
              'uid': 'cbf3b107-2729-48ce-92ba-c454051a00db',
              'x': {'bdata': ('AAABAAIAAwAEAAUABgAHAAgACQAKAA' ... 'RCBEMERARFBEYERwRIBEkESgRLBEwE'),
                    'dtype': 'i2'},
              'xaxis': 'x3',
              'y': {'bdata': ('AQAAAAEAAAABAAAAAQAAAAEAAAABAA' ... 'AAAAEAAAABAAAAAQAAAAEAAAABAAAA'),
                    'dtype': 'i4'},
              'yaxis': 'y3'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Orders',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Trade PnL',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.6527777777777777,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Cumulative Returns',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.3055555555555555,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'height': 960,
               'legend': {'orientation': 'h',
                          'traceorder': 'normal',
                          'x': 1,
                          'xanchor': 'right',
                          'y': 1.0416666666666667,
                          'yanchor': 'bottom'},
               'margin': {'b': 30, 'l': 30, 'r': 30, 't': 30},
               'shapes': [{'line': {'color': 'gray', 'dash': 'dash'},
                           'type': 'line',
                           'x0': 0.0,
                           'x1': 1.0,
                           'xref': 'paper',
                           'y0': 0,
                           'y1': 0,
                           'yref': 'y2'},
                          {'line': {'color': 'gray', 'dash': 'dash'},
                           'type': 'line',
                           'x0': 0.0,
                           'x1': 1.0,
                           'xref': 'paper',
                           'y0': 1,
                           'y1': 1,
                           'yref': 'y3'}],
               'showlegend': True,
               'template': '...',
               'width': 750,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'matches': 'x3', 'showticklabels': False},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x3', 'showticklabels': False},
               'xaxis3': {'anchor': 'y3', 'domain': [0.0, 1.0], 'title': {'text': 'Index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.6944444444444444, 1.0], 'title': {'text': 'Price'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.3472222222222222, 0.6527777777777777],
                          'tickformat': '.2%',
                          'title': {'text': 'Trade PnL'}},
               'yaxis3': {'anchor': 'x3', 'domain': [0.0, 0.3055555555555555], 'title': {'text': 'Cumulative returns'}}}
})

In [54]:
dir(p)

['__annotations__',
 '__cached_asset_flow',
 '__cached_asset_value',
 '__cached_assets',
 '__cached_benchmark_returns',
 '__cached_benchmark_value',
 '__cached_cash',
 '__cached_cash_flow',
 '__cached_exit_trades',
 '__cached_final_value',
 '__cached_get_drawdowns',
 '__cached_get_exit_trades',
 '__cached_get_filled_close',
 '__cached_get_init_cash',
 '__cached_get_orders',
 '__cached_get_positions',
 '__cached_get_returns_acc',
 '__cached_get_trades',
 '__cached_gross_exposure',
 '__cached_orders',
 '__cached_positions',
 '__cached_returns',
 '__cached_total_profit',
 '__cached_total_return',
 '__cached_trades',
 '__cached_value',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_call_seq',
 '_cash_sharing',
 '_close',
 '_config',
 '_fillna_close',
 '_iloc',
 '_indexing_kwargs',
 '_init_cash',
 '_loc',
 '_log_records',
 '_metrics',
 '_order_records',
 '_subplots',
 '_trades_type',
 '_wrapper',
 'alpha',
 'annual_returns',
 'annualized_return',
 'annualized_volatility',
 'asset_flow',
 'asset_returns',
 'asset_value',
 'assets',
 'benchmark_rets',
 'benchmark_returns',
 'benchmark_value',
 'beta',
 'build_metrics_doc',
 'build_subplots_doc',
 'call_seq',
 'calmar_ratio',
 'capture',
 'cash',
 'cash_flow',
 'cash_sharing',
 'close',
 'cond_value_at_risk',
 'config',
 'copy',
 'cumulative_returns',
 'daily_returns',
 'deep_getattr',
 'deflated_sharpe_ratio',
 'down_capture',
 'downside_risk',
 'drawdown',
 'drawdowns',
 'dumps',
 'entry_trades',
 'exit_trades',
 'fillna_close',
 'final_value',
 'from_holding',
 'from_order_func',
 'from_orders',
 'from_random_signals',
 'from_signals',
 'get_drawdowns',
 'get_entry_trades',
 'get_exit_trades',
 'get_filled_close',
 'get_init_cash',
 'get_logs',
 'get_orders',
 'get_positions',
 'get_qs',
 'get_returns_acc',
 'get_trades',
 'gross_exposure',
 'iloc',
 'indexing_func',
 'indexing_kwargs',
 'information_ratio',
 'init_cash',
 'load',
 'loads',
 'loc',
 'log_records',
 'logs',
 'max_drawdown',
 'metrics',
 'net_exposure',
 'omega_ratio',
 'order_records',
 'orders',
 'override_metrics_doc',
 'override_subplots_doc',
 'plot',
 'plot_asset_flow',
 'plot_asset_value',
 'plot_assets',
 'plot_cash',
 'plot_cash_flow',
 'plot_cum_returns',
 'plot_drawdowns',
 'plot_gross_exposure',
 'plot_net_exposure',
 'plot_orders',
 'plot_position_pnl',
 'plot_positions',
 'plot_trade_pnl',
 'plot_trades',
 'plot_underwater',
 'plot_value',
 'plots',
 'plots_defaults',
 'position_coverage',
 'position_mask',
 'positions',
 'post_resolve_attr',
 'pre_resolve_attr',
 'qs',
 'regroup',
 'replace',
 'resolve_attr',
 'resolve_self',
 'returns',
 'returns_acc',
 'returns_stats',
 'save',
 'select_one',
 'select_one_from_obj',
 'self_aliases',
 'sharpe_ratio',
 'sortino_ratio',
 'stats',
 'stats_defaults',
 'subplots',
 'tail_ratio',
 'to_doc',
 'total_benchmark_return',
 'total_profit',
 'total_return',
 'trades',
 'trades_type',
 'up_capture',
 'update_config',
 'value',
 'value_at_risk',
 'wrapper',
 'writeable_attrs',
 'xs']